[connections.gsheets]
spreadsheet1 = "https://docs.google.com/spreadsheets/d/17WqhzBjUjL7odp_O1BBvJPjQoVsPiH76DKMKRMWoEqA/edit?usp=sharing"
spreadsheet2 = "https://docs.google.com/spreadsheets/d/1m_wAZC2vZoQwoP2lPruervU37a4VBUFvwcJYYrE6dSw/edit?usp=sharing"